//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calender.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int EventId { get; set; }
        public System.Guid TutorId { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> DateOfClass { get; set; }
        public string Description { get; set; }
        public System.DateTimeOffset StartTime { get; set; }
        public System.DateTimeOffset EndTime { get; set; }
        public Nullable<System.DateTimeOffset> CreatedAt { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedAt { get; set; }
        
    
        public virtual Tutor Tutor { get; set; }
    }
}
